language: bash

install:
  - wget https://github.com/gohugoio/hugo/releases/download/v0.38.2/hugo_0.38.2_Linux-64bit.deb
  - sudo dpkg -i hugo*.deb

script:
  - hugo

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_API_TOKEN
  keep-history: true
  local-dir: public
  target-branch: master
  on:
    branch: hugo

branches:
  only:
    - hugo
