#
###################################
# Site wide configuration
####################################
#
title: Marcin Chmiel
email:
description: "mewa's personal tech blog"
url: http://marcinchmiel.com


#
###################################
# Jekyll configuration
####################################
#
timezone:          Europe/Paris
markdown:          kramdown
highlighter:       rouge
excerpt_separator: <!--more-->
permalink:         /articles/:year-:month/:title

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  enable_coderay: false

#
###################################
# Site Owner configuration
####################################
#
owner:
  name: Marcin Chmiel
  avatar: #none
  job: "Software Magician"
  bio: "Mobile guru, cloud architect, Haskell freak. This is where I share some of the things I happen to find interesting or helpful otherwise."
  email: "marcin@marcinchmiel.com"
  disqus-shortname: mewa
  twitter: mewadev
  facebook: #username
  google:
    plus: #username
    analytics: UA-99152208-1
    verify:
    ad-client:
    ad-slot:
  bing-verify:
  github: mewa
  gitlab: #username
  stackoverflow: #123456/username   from a "http://stackoverflow.com/users/123456/username" link
  linkedin: #username
  skype: #username
  xing: #username
  instagram: #username
  lastfm: #username
  tumblr: #username
  pinterest: #username
  foursquare: #username
  steam: #username
  dribbble: #username
  youtube: #username
  soundcloud: #username
  weibo: #username
  flickr: #username
  500px: #username
  codepen: #username
