baseURL = "http://marcinchmiel.com"
footnoteReturnLinkContents = "↩"
title = "Marcin Chmiel"
theme = "hugo_theme_pickles"
disqusShortname = "mewa"

pygmentsCodefences = true
pygmentsStyle = "github"

relativeURLs = true

[taxonomies]
    # Optional. Use if you want tags and lists.
    category = "categories" 

[params]
    twitter = "mewadev"
    github = "mewa"
    linkedin = "mkchmiel"
    
    subtitle = "This is where I share some of the things I happen to find interesting or helpful otherwise"

    contact = "mailto:m@marcinchmiel.com"

    avatar = "https://media.licdn.com/dms/image/C5603AQEzkExb7j1zIg/profile-displayphoto-shrink_200_200/0?e=1528732800&v=beta&t=lX_9uf9HQYc_UM9gBv2m-OCzl6pn1uUZ9uylqtFUd-M"

    author = "Marcin Chmiel"
    bio = "Software magician, cloud architect, functional programming freak"

    ga_api_key = "UA-99152208-1"

[menu]

  [[menu.main]]
    name = "Blog"
    url = "/"
    weight = -110

  [[menu.main]]
    name = "Categories"
    url = "/categories/"
    weight = -100

[permalinks]
    posts = "articles/:year-:month/:title/"