baseURL = "https://marcinchmiel.com/"
footnoteReturnLinkContents = "↩"
title = "Marcin Chmiel"
theme = "hugo_theme_pickles"
disqusShortname = "mewa"

pygmentsCodefences = true
pygmentsStyle = "github"

relativeURLs = true

googleAnalytics = "UA-99152208-1"

[taxonomies]
    # Optional. Use if you want tags and lists.
    category = "categories" 

[params]
    twitter = "marcin_chm"
    github = "mewa"
    linkedin = "mkchmiel"
    
    subtitle = "This is where I share some of the things I happen to find interesting or helpful otherwise"

    contact = "https://twitter.com/intent/user?screen_name=marcin_chm"

    avatar = "/img/avatar.jpg"

    author = "Marcin Chmiel"
    bio = "Indie hacker and serial maker. Always working on something. Passionate about cloud technologies, in particular containers & serverless."

[menu]

  [[menu.main]]
    name = "Blog"
    url = "/"
    weight = -110

  [[menu.main]]
    name = "Categories"
    url = "/categories/"
    weight = -100

[permalinks]
    posts = "articles/:year-:month/:title/"